server.port=8081
server.servlet.session.cookie.name=BANK_SESSION

# RabbitMQ properties
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Custom exchanges and queues, used internally or as constants
app.rabbitmq.exchange=credit.exchange
app.rabbitmq.request.queue=credit.request.queue
app.rabbitmq.request.routingkey=credit.request.routingkey
app.rabbitmq.response.queue=credit.response.queue
app.rabbitmq.response.routingkey=credit.response.routingkey
